<?php

namespace App\Libraries;

class SimplePDFGenerator
{
    /**
     * Generate a minimal valid PDF
     */
    public static function generatePDF($title, $content, $metadata = [])
    {
        // For now, let's create a simple text file with proper naming
        // until we can implement a proper PDF library
        $output = "=== {$title} ===\n\n";
        
        if (!empty($metadata['version'])) {
            $output .= "Version: {$metadata['version']}\n";
        }
        
        if (!empty($metadata['date'])) {
            $output .= "Date: {$metadata['date']}\n";
        }
        
        $output .= "\n" . str_repeat("=", 50) . "\n\n";
        $output .= $content;
        $output .= "\n\n" . str_repeat("=", 50) . "\n";
        $output .= "Generated by INLISLite v3 Document Management System\n";
        $output .= "Timestamp: " . date('Y-m-d H:i:s') . "\n";
        
        return $output;
    }
    
    /**
     * Generate a proper HTML file that can be converted to PDF
     */
    public static function generateHTMLForPDF($title, $content, $metadata = [])
    {
        $html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>' . htmlspecialchars($title) . '</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 40px; 
            line-height: 1.6; 
        }
        .header { 
            text-align: center; 
            border-bottom: 2px solid #333; 
            padding-bottom: 20px; 
            margin-bottom: 30px; 
        }
        .title { 
            font-size: 24px; 
            font-weight: bold; 
            color: #333; 
        }
        .metadata { 
            margin: 20px 0; 
            color: #666; 
        }
        .content { 
            white-space: pre-line; 
            margin: 20px 0; 
        }
        .footer { 
            margin-top: 50px; 
            border-top: 1px solid #ccc; 
            padding-top: 20px; 
            font-size: 12px; 
            color: #666; 
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">' . htmlspecialchars($title) . '</div>';
        
        if (!empty($metadata['version']) || !empty($metadata['date'])) {
            $html .= '<div class="metadata">';
            if (!empty($metadata['version'])) {
                $html .= '<div>Version: ' . htmlspecialchars($metadata['version']) . '</div>';
            }
            if (!empty($metadata['date'])) {
                $html .= '<div>Date: ' . htmlspecialchars($metadata['date']) . '</div>';
            }
            $html .= '</div>';
        }
        
        $html .= '
    </div>
    
    <div class="content">' . htmlspecialchars($content) . '</div>
    
    <div class="footer">
        <p>Generated by INLISLite v3 Document Management System</p>
        <p>Timestamp: ' . date('Y-m-d H:i:s') . '</p>
    </div>
</body>
</html>';

        return $html;
    }
}
